site_name: Pars Downloads
site_url: https://downloads.parsdevkit.net/
site_description: Pars Downloads
repo_url: https://github.com/parsdevkit/pars
repo_name: parsdevkit/pars
edit_uri: https://github.com/parsdevkit/pars-downloads/edit/main/contents/
docs_dir: contents
nav:
  - Download: pars/index.md
  - Archives: pars/archives/index.md
  - Change Logs: pars/changelogs/index.md

theme:
  name: material
  analytics:
    provider: google
    property: G-TNGBBETP6J
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/parsdevkit/pars/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.

  language: en
  custom_dir: theme
  favicon: assets/favicon.png
  font:
    code: Roboto Mono
  icon:
    logo: material/access-point
    annotation: material/arrow-right-circle-outline
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    tag:
      default: fontawesome/solid/tag
      html5: fontawesome/brands/html5
      javascript: fontawesome/brands/js
      css: fontawesome/brands/css3
      php: fontawesome/brands/php
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
  - i18n:
      docs_structure: folder
      default_language: en
      material_alternate: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Pars Downloads"
          site_description: "Pars Downloads"
  - info:
      enabled: false
  # - autorefs:
  # - group:
  #     enabled: !ENV CI
  # - optimize
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  # - meta:
      # meta_file: .meta.yml
  #     enabled: false
  # - redirects
  - offline
  - mermaid2
  - tags:
      tags_file: extras/tags.md
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: 
        - en
        - tr
  # - social
  # - blog
  # - glightbox
  - privacy:
      enabled: !ENV [CI, false]
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-committers:
  #     repository: parsdevkit/pars
  #     branch: main
  # - git-authors
  - ezglossary:
      markdown_links: true
      list_definitions: false
      # use_default: true
      tooltip: full
      inline_refs: short
      # sections:
      #   - terms
      #   - demo

hooks:
  - theme/hooks/socialmedia.py
extra:
  homepage: http://downloads.parsdevkit.net/
  version:
    provider: mike
    default: latest
    alias: true
  status:
    new: Recently added
    deprecated: Deprecated
  scope: /
  tags:
    html5: html5
    HTML5: html5
    JavaScript: javascript
    javascript: javascript
    css: css
    CSS: css
    CSS3: css
    PHP: php
    php: php
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@parsdevkit.net
    - icon: fontawesome/brands/github 
      link: https://github.com/parsdevkit/pars
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/groups/13072322/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ParsDevKit
    - icon: fontawesome/brands/medium
      link: https://medium.com/@parsdevkit
  generator: false
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
      - manage
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2017 - 2024 Pars –
  <a href="#__consent">Change cookie settings</a>
markdown_extensions:
  # Python Markdown
  # - mdx_spanner
  # - codeblockheader
  - abbr
  - admonition
  - attr_list
  - wikilinks:
      # wiki_base_url: http://google.com
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: "#"
      # baselevel: 2
      # separator: "_"
      title: On this page
      # toc_depth: 3
      permalink_title: Anchor link to this section for reference
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower

  # Python Markdown Extensions
  # - pymdownx.blocks.admonition
  # - pymdownx.blocks.define
  # - pymdownx.blocks.details
  # - pymdownx.blocks.tab
  # - pymdownx.blocks.html
  - pymdownx.saneheaders
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      # auto_title: true
      # linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.magiclink:
      repo_url_shortener: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: prefix
        #   class: prefix
        #   format: !!python/name:custom_doc_tools.superfences.prefix_code_format
        # - name: diagram
        #   class: diagram
        #   format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: math
        #   class: arithmatex
        #   format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
        # - name: md-render
        #   class: md-render
        #   format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
  - pymdownx.critic:
      mode: view
  - pymdownx.snippets:
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/custom.css
extra_javascript:
  # - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  # - assets/javascripts/tablesort.js
  - assets/javascripts/mathjax.js
watch:
  - theme
# use_directory_urls: true